### PR TITLE
Fix NSDate precision loss causing -isEqualToDate: to fail

### PR DESCRIPTION
**Pull request by fabiankr**
In a project I'm working on we noticed an issue with serializing dates. The model object in question has multiple `NSDate` objects and in its `-isEqual:` method it checks the dates by calling `-isEqualToDate`. Now one of our tests seemed to fail randomly, because `-isEqual:` returned `NO` after encoding and decoding the object using FastCoder which caused our project to do unexpected things as the object didn't really change.

Specifically, the following assertion fails:

    NSDate *input = [NSDate dateWithTimeIntervalSinceReferenceDate:542911754.16538298];
    NSDate *decodedInput = [FastCoder objectWithData:[FastCoder dataWithRootObject:input]];
    XCTAssertTrue([input isEqualToDate: decodedInput]);

This happens because `NSDate` stores `-timeIntervalSinceReferenceDate` internally rather than `-timeIntervalSince1970`. FastCoder relies on `-timeIntervalSince1970` and that causes the equality check to fail due to floating point conversion.

See `NSDate`'s implementation (decompiled using Hopper):
timeintervalsincereferencedate
isequaltodate

The actual change to fix the issue in `FCReadDate()` and `-[NSDate FC_encodeWithCoder:]` is rather simple, but in order to guarantee backwards-compatibility I had to make the version information accessible to `FCReadDate()`.

In the unit tests `-testDateEquality` should always fail without the fix while `-testChangingModel` only fails about 50% of the time depending on the current date.

### CODE REVIEW

**Comment by nicklockwood** [comment]
Great PR, thanks for thinking about backwards compatibility!

The only slight issue is that older versions of FastCoding that encounter a file generated by version 3.3 are going to fail silently. I have a workaround for that though.

**Comment by fabiankr** [comment]
Oh yeah I didn't think about that because in our case that can't happen. Thanks! :)

**Comment by nicklockwood** [comment]
@fabiankr OK, I've pushed my fix and tagged version 3.3

**Comment by fabiankr** [comment]
With your fix the iVar `_header` in FCNSDecoder is no longer needed. Feel free to remove it if you want. I think relying on that will always cause issues with older versions of FastCoding and new archives.

**Comment by nicklockwood** [comment]
@fabiankr ah, good point. Well, it's harmless so I'll leave it until the next release.

**Pull request merged**
